[package]
version = "1.0.1"
category = "Simulation"
title = "Loaded Scenario Template"
description = "Loaded Scenario Template"
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.api" = {}
"isaacsim.gui.components" = {}
"omni.kit.uiapp" = {}

[[python.module]]
name = "Loaded_Scenario_Template_python"
